app = "tern"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[env]
  XDG_DATA_HOME = "/data/certmagic"

[processes]
  app = "/tern --domain tern.fly.dev --acme-email marcelo@cantos.id.au"

[[services]]
  internal_port = 443
  protocol = "udp"
  processes = ["app"]

  [[services.ports]]
    port = 443

[[services]]
  internal_port = 443
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 443

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
